//! Offline license validation for the Tyverix subscription.
//!
//! License keys are Ed25519-signed tokens of the form `payload.signature`
//! (both base64url). The payload carries the buyer's email, tier and an expiry
//! date. Because the app embeds only the *public* key, keys can be verified
//! completely offline and cannot be forged without the private signing key.
//!
//! A monthly subscription is simply a key with a ~31-day expiry that the vendor
//! re-issues each billing cycle (see `tools/sign-license.mjs`). The free trial
//! is account-based (1 day from registration) and handled in the frontend
//! against the Supabase account — this module only deals with signed keys.

use base64::Engine;
use chrono::{Local, NaiveDate};
use ed25519_dalek::{Signature, VerifyingKey};
use serde::{Deserialize, Serialize};

use crate::error::{AppError, AppResult};
use crate::util::app_data_dir;

/// Raw 32-byte Ed25519 public key (base64url) — generated by
/// `tools/license-keygen.mjs`. Replace this if you regenerate the key pair.
const LICENSE_PUBLIC_KEY: &str = "5z4VDcSR_nSk4Sqdls51utInFoXp8PdcNBt5b8t0VfY";

#[derive(Serialize, Deserialize)]
struct Payload {
    id: String,
    email: String,
    tier: String,
    issued: String,
    expires: String,
}

#[derive(Serialize)]
pub struct LicenseStatus {
    /// "free" | "trial" | "pro"
    pub tier: String,
    /// True when Pro features should be unlocked (paid or trial).
    pub valid: bool,
    pub email: Option<String>,
    pub expires: Option<String>,
    pub days_remaining: Option<i64>,
    pub trial_days_remaining: Option<i64>,
    pub reason: Option<String>,
}

fn b64() -> base64::engine::GeneralPurpose {
    base64::engine::general_purpose::URL_SAFE_NO_PAD
}

fn license_path() -> AppResult<std::path::PathBuf> {
    Ok(app_data_dir()?.join("license.key"))
}

fn verifying_key() -> AppResult<VerifyingKey> {
    let bytes = b64()
        .decode(LICENSE_PUBLIC_KEY)
        .map_err(|e| AppError::other(format!("bad embedded public key: {e}")))?;
    let arr: [u8; 32] = bytes
        .try_into()
        .map_err(|_| AppError::other("embedded public key must be 32 bytes"))?;
    VerifyingKey::from_bytes(&arr).map_err(|e| AppError::other(e.to_string()))
}

/// Verifies a key's signature and returns its payload (does not check expiry).
fn verify_key(key: &str) -> Result<Payload, String> {
    let (payload_b64, sig_b64) = key
        .trim()
        .split_once('.')
        .ok_or_else(|| "malformed license key".to_string())?;

    let sig_bytes = b64()
        .decode(sig_b64)
        .map_err(|_| "malformed signature".to_string())?;
    let signature =
        Signature::from_slice(&sig_bytes).map_err(|_| "invalid signature length".to_string())?;

    let vk = verifying_key().map_err(|e| e.to_string())?;
    vk.verify_strict(payload_b64.as_bytes(), &signature)
        .map_err(|_| "signature does not match (invalid or tampered key)".to_string())?;

    let payload_bytes = b64()
        .decode(payload_b64)
        .map_err(|_| "malformed payload".to_string())?;
    serde_json::from_slice::<Payload>(&payload_bytes)
        .map_err(|_| "unreadable payload".to_string())
}

fn days_until(date: &str) -> Option<i64> {
    let d = NaiveDate::parse_from_str(date, "%Y-%m-%d").ok()?;
    Some((d - Local::now().date_naive()).num_days())
}

/// The baseline status when no valid paid key is present. The free trial is
/// account-based and applied by the frontend, so this stays plain "free".
fn free_status() -> LicenseStatus {
    LicenseStatus {
        tier: "free".into(),
        valid: false,
        email: None,
        expires: None,
        days_remaining: None,
        trial_days_remaining: None,
        reason: None,
    }
}

#[tauri::command]
pub fn get_license_status() -> AppResult<LicenseStatus> {
    let path = license_path()?;
    let Ok(key) = std::fs::read_to_string(&path) else {
        return Ok(free_status());
    };

    match verify_key(&key) {
        Ok(payload) => {
            let days = days_until(&payload.expires);
            let valid = days.map(|d| d >= 0).unwrap_or(false);
            Ok(LicenseStatus {
                tier: if valid { payload.tier.clone() } else { "free".into() },
                valid,
                email: Some(payload.email),
                expires: Some(payload.expires),
                days_remaining: days,
                trial_days_remaining: None,
                reason: if valid {
                    None
                } else {
                    Some("subscription expired — please renew".into())
                },
            })
        }
        // A stored-but-invalid key falls back to free rather than erroring.
        Err(reason) => {
            let mut status = free_status();
            status.reason = Some(reason);
            Ok(status)
        }
    }
}

#[tauri::command]
pub fn activate_license(key: String) -> AppResult<LicenseStatus> {
    let payload = verify_key(&key).map_err(AppError::other)?;
    let days = days_until(&payload.expires);
    if days.map(|d| d < 0).unwrap_or(true) {
        return Err(AppError::other(
            "this license key has expired — please renew your subscription",
        ));
    }
    std::fs::write(license_path()?, key.trim())?;
    get_license_status()
}

#[tauri::command]
pub fn deactivate_license() -> AppResult<LicenseStatus> {
    let path = license_path()?;
    if path.exists() {
        std::fs::remove_file(path)?;
    }
    get_license_status()
}
